name: universal_date
description: universal_date project
version: 2026.108.1122
homepage: 
repository: https://github.com/dart-pkg/universal_date
environment:
  sdk: ^3.7.2
# executables:
#  universal-date: main
dependencies:
  intl: ^0.20.2
  timeago: ^3.7.1
dev_dependencies:
  test: ^1.29.0
  lints: ^6.0.0
